const P2_COURSES = [
{
    "version": "1.0",
    "period": "2",
    "validFrom": "2026-2027",
    "courses": [
    {
        "slot": "A",
        "code": "BIO1101",
        "title": "CORE: Introduction to Biology",
        "coordinator": "David Cortens",
        "corequisite": true,
        "prerequisite": false,
        "days": ["MonAM", "TueAM"],
        "corequisiteOf": "PRA1102",
        "prerequisiteCodes": null
    },
    {
        "slot": "A",
        "code": "BIO3007",
        "title": "Tropical Biology",
        "coordinator": "Roy Erkens",
        "corequisite": false,
        "prerequisite": true,
        "days": ["MonAM", "TueAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "BIO2002"
    },
    {
        "slot": "A",
        "code": "CHE2011",
        "title": "Organic Chemistry",
        "coordinator": "Hanne Diliën",
        "corequisite": true,
        "prerequisite": true,
        "days": ["MonAM", "TueAM"],
        "corequisiteOf": "PRA2033",
        "prerequisiteCodes": "CHE2009"
    },
    {
        "slot": "A",
        "code": "INT3007",
        "title": "Systems Biology",
        "coordinator": "Martina Summer-Kutmon & Judith Peters",
        "corequisite": false,
        "prerequisite": true,
        "days": ["MonAM", "TueAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "PRO1002"
    },
    {
        "slot": "A",
        "code": "PHY3008",
        "title": "Cosmology",
        "coordinator": "Lorenzo Reverberi",
        "corequisite": false,
        "prerequisite": true,
        "days": ["MonAM", "TueAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "MAT2009+PHY2011+PHY2008+PHY2009+PHY2010"
    },
    {
        "slot": "B",
        "code": "INT3012",
        "title": "Science Education: Model-Based Inquiry",
        "coordinator": "May Lee",
        "corequisite": true,
        "prerequisite": true,
        "days": ["MonPM", "TuePM"],
        "corequisiteOf": "PRA3026",
        "prerequisiteCodes": "INT2013"
    },
    {
        "slot": "B",
        "code": "INT2007",
        "title": "Science in Action",
        "coordinator": "Jessica Mesman",
        "corequisite": false,
        "prerequisite": false,
        "days": ["MonPM", "TuePM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": "B",
        "code": "MAT2009",
        "title": "Multivariable Calculus",
        "coordinator": "Mariet Hofstee",
        "corequisite": false,
        "prerequisite": true,
        "days": ["MonPM", "TuePM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "MAT2006+MAT2004"
    },
    {
        "slot": "B",
        "code": "PHY3004",
        "title": "Elementary Particle Physics",
        "coordinator": "Marcel Merk & Jacco de Vries",
        "corequisite": true,
        "prerequisite": true,
        "days": ["MonPM", "TuePM"],
        "corequisiteOf": "MAT2006",
        "prerequisiteCodes": "PHY2005+MAT2004"
    },
    {
        "slot": "B",
        "code": "NEU2004",
        "title": "Neural Circuits and Dynamics",
        "coordinator": "Luke Edwards",
        "corequisite": false,
        "prerequisite": false,
        "days": ["MonPM", "TuePM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": "C",
        "code": "BIO3001",
        "title": "Molecular Biology",
        "coordinator": "Kathia Jimenez Monroy",
        "corequisite": true,
        "prerequisite": true,
        "days": ["TueAM", "WedAM"],
        "corequisiteOf": "PRA3003",
        "prerequisiteCodes": "BIO2001+BIO2007"
    },
    {
        "slot": "C",
        "code": "INT1101",
        "title": "CORE: Introduction to Liberal Arts & Sciences",
        "coordinator": "Hanne Diliën, Rocio Arreguin Campos",
        "corequisite": true,
        "prerequisite": false,
        "days": ["TueAM", "WedAM"],
        "corequisiteOf": "PRA1102",
        "prerequisiteCodes": null
    },
    {
        "slot": "C",
        "code": "INT3005",
        "title": "Biobased Materials and Technology",
        "coordinator": "Yvonne van der Meer & Katie Saralidze",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TueAM", "WedAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": "C",
        "code": "PHY2010",
        "title": "Galactic Astronomy",
        "coordinator": "Chad Ellington",
        "corequisite": false,
        "prerequisite": false,
        "days": ["TueAM", "WedAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": "D",
        "code": "INT3009",
        "title": "Chemical Ecology",
        "coordinator": "John Sloggett",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TuePM", "WedPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "BIO2001/CHE2009"
    },
    {
        "slot": "D",
        "code": "CHE2006",
        "title": "Biochemistry *",
        "coordinator": "Leon Schurgers & Niko Deckers",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TuePM", "WedPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "BIO1101/CHE1101"
    },
    {
        "slot": "D",
        "code": "CHE3013",
        "title": "Advanced Organic Chemistry",
        "coordinator": "Matt Baker",
        "corequisite": true,
        "prerequisite": true,
        "days": ["TuePM", "WedPM"],
        "corequisiteOf": "PRA3029",
        "prerequisiteCodes": "CHE2011"
    },
    {
        "slot": "D",
        "code": "PHY2003",
        "title": "Vibrations and Waves",
        "coordinator": "Jessica Steinlechner",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TuePM", "WedPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "PHY2001"
    },
    {
        "slot": "E",
        "code": "BIO2008",
        "title": "Great Transformations in Vertebrate Evolution",
        "coordinator": "Leon Claessens",
        "corequisite": true,
        "prerequisite": false,
        "days": ["WedAM", "ThuAM"],
        "corequisiteOf": "PRA2025",
        "prerequisiteCodes": null
    },
    {
        "slot": "E",
        "code": "CHE3007",
        "title": "Chemical Kinetics",
        "coordinator": "Slava Vieru",
        "corequisite": false,
        "prerequisite": true,
        "days": ["WedAM", "ThuAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "MAT2006+PHY2002"
    },
    {
        "slot": "E",
        "code": "MAT1006",
        "title": "Applied Statistics",
        "coordinator": "Matthijs Hermeling",
        "corequisite": false,
        "prerequisite": false,
        "days": ["WedAM", "ThuAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": "E",
        "code": "NEU3003",
        "title": "Brain-Body Interactions",
        "coordinator": "Michelle Moerel",
        "corequisite": false,
        "prerequisite": true,
        "days": ["WedAM", "ThuAM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "NEU1001+NEU2005+BIO2010"
    },
    {
        "slot": null,
        "code": "PRA1102",
        "title": "Introduction to Scientific Research II",
        "coordinator": "Suzan du Pree",
        "corequisite": true,
        "prerequisite": true,
        "days": ["WedAM", "WedPM"],
        "corequisiteOf": "BIO1101",
        "prerequisiteCodes": "MSP1000"
    },
    {
        "slot": null,
        "code": "PRA1003",
        "title": "Basic Physics Laboratory",
        "coordinator": "Chris Pawley",
        "corequisite": false,
        "prerequisite": false,
        "days": ["WedAM", "WedPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": null,
        "code": "PRA2010",
        "title": "Synthetic Biology",
        "coordinator": "Erik Steen Redeker",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TueAM", "TuePM", "ThuAM", "ThuPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": null,
        "code": "PRA2013",
        "title": "Practical Zoology",
        "coordinator": "John Sloggett",
        "corequisite": false,
        "prerequisite": true,
        "days": ["WedAM", "WedPM", "ThuAM", "ThuPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "PRA1102+BIO2004"
    },
    {
        "slot": null,
        "code": "PRA2018",
        "title": "Capita Selecta in Modern Sciences",
        "coordinator": "Panos Christakoglou",
        "corequisite": false,
        "prerequisite": false,
        "days": ["MonAM", "MonPM", "TueAM", "TuePM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    },
    {
        "slot": null,
        "code": "PRA2025",
        "title": "Vertebrate Functional Morphology",
        "coordinator": "Leon Claessens & Jesse Hennekam",
        "corequisite": true,
        "prerequisite": false,
        "days": ["ThuAM", "ThuPM"],
        "corequisiteOf": "BIO2008",
        "prerequisiteCodes": null
    },
    {
        "slot": null,
        "code": "PRA2033",
        "title": "Organic Chemistry Laboratory",
        "coordinator": "Hanne Diliën",
        "corequisite": true,
        "prerequisite": true,
        "days": ["TueAM", "TuePM", "ThuAM", "ThuPM"],
        "corequisiteOf": "CHE2011",
        "prerequisiteCodes": "PRA2032"
    },
    {
        "slot": null,
        "code": "PRA3029",
        "title": "Advanced Organic Chemistry Laboratory",
        "coordinator": "Matt Baker",
        "corequisite": true,
        "prerequisite": true,
        "days": ["MonAM", "MonPM"],
        "corequisiteOf": "CHE3013",
        "prerequisiteCodes": "CHE2011"
    },
    {
        "slot": null,
        "code": "PRA3002",
        "title": "Advanced Physics Laboratory",
        "coordinator": "Chris Pawley",
        "corequisite": false,
        "prerequisite": true,
        "days": ["TueAM", "TuePM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "PRA1003/PRA2007"
    },
    {
        "slot": null,
        "code": "PRA3003",
        "title": "Molecular Biology",
        "coordinator": "Kathia Jimenez Monroy",
        "corequisite": true,
        "prerequisite": true,
        "days": ["MonAM", "MonPM", "WedAM", "WedPM"],
        "corequisiteOf": "BIO3001",
        "prerequisiteCodes": "PRA2014"
    },
    {
        "slot": null,
        "code": "PRA3005",
        "title": "Polymer Processing *",
        "coordinator": "Eveline Maassen",
        "corequisite": false,
        "prerequisite": true,
        "days": ["MonAM", "MonPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "CHE2001"
    },
    {
        "slot": null,
        "code": "PRA3006",
        "title": "Programming in the Life Sciences",
        "coordinator": "Egon Willighagen & Rianne Fijten",
        "corequisite": false,
        "prerequisite": true,
        "days": ["FriAM", "FriPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "MAT2007/PRA2003"
    },
    {
        "slot": null,
        "code": "PRA3023",
        "title": "Plant Physiology and Microbiomes **",
        "coordinator": "Aleksandr Umanets",
        "corequisite": false,
        "prerequisite": true,
        "days": ["FriAM", "FriPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "BIO2003"
    },
    {
        "slot": null,
        "code": "PRA3026",
        "title": "Science Teaching Skills",
        "coordinator": "May Lee",
        "corequisite": true,
        "prerequisite": true,
        "days": ["WedAM", "WedPM"],
        "corequisiteOf": "INT3012",
        "prerequisiteCodes": "INT2013"
    },
    {
        "slot": null,
        "code": "PRA3027",
        "title": "Advanced Functional Morphology",
        "coordinator": "Leon Claessens & Jesse Hennekam",
        "corequisite": false,
        "prerequisite": true,
        "days": ["ThuAM", "ThuPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": "PRA2025"
    },
    {
        "slot": null,
        "code": "PRA3031",
        "title": "Statistical Modeling",
        "coordinator": "Joao da Cruz Vargas",
        "corequisite": false,
        "prerequisite": false,
        "days": ["TueAM", "TuePM", "FriAM", "FriPM"],
        "corequisiteOf": null,
        "prerequisiteCodes": null
    }
    ]
  }
];