const P4_COURSES = [
    {
        "version": "1.0",
        "period": "4",
        "validFrom": "2026-2027",
        "courses": [
            {
                "slot": "A",
                "code": "BIO2003",
                "title": "General Botany",
                "coordinator": "Phil Klahs",
                "corequisite": true,
                "prerequisite": false,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": "PRA2011",
                "prerequisiteCodes": null
            },
            {
                "slot": "A",
                "code": "BIO3010",
                "title": "Genomics, Proteomics and Other Omics Technologies",
                "coordinator": "Birol Cabukusta",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "BIO1101+BIO2007+BIO3001+CHE2006"
            },
            {
                "slot": "A",
                "code": "CHE2009",
                "title": "Fundamentals of Organic Chemistry *",
                "coordinator": "Hanne Diliën",
                "corequisite": true,
                "prerequisite": false,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": "PRA2032",
                "prerequisiteCodes": null
            },
            {
                "slot": "A",
                "code": "CHE3009",
                "title": "Crystallography",
                "coordinator": "Giuditta Perversi",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRO1002+CHE2007+CHE2002+MAT2004"
            },
            {
                "slot": "A",
                "code": "PHY3010",
                "title": "Lasers and Applications",
                "coordinator": "Anna Green",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY2005+MAT2006+MAT2004+PHY2007"
            },
            {
                "slot": "B",
                "code": "BIO2005",
                "title": "Evolutionary Biology",
                "coordinator": "Linnea van Griethuijsen",
                "corequisite": true,
                "prerequisite": false,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": "BIO2007",
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "BIO2010",
                "title": "Human Anatomy & Physiology",
                "coordinator": "Aaron Isaacs",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "MAT2006",
                "title": "Calculus",
                "coordinator": "Niloufar Yousefimanesh",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "MAT2008",
                "title": "Differential Equations",
                "coordinator": "Mariët Hofstee",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "NEU3002",
                "title": "Brain-Inspired Engineering",
                "coordinator": "Renaud Jolivet",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "NEU1003/INT1003"
            },
            {
                "slot": "C",
                "code": "BIO2007",
                "title": "Genetics",
                "coordinator": "Leon de Windt",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": "PRA2014",
                "prerequisiteCodes": "BIO2001"
            },
            {
                "slot": "C",
                "code": "INT2010",
                "title": "Principles of Mass Spectrometry",
                "coordinator": "Ian Anthony",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "C",
                "code": "NEU1001",
                "title": "Introduction to Neuroscience",
                "coordinator": "Laurence de Nijs",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "C",
                "code": "INT2012",
                "title": "Archaeological Science",
                "coordinator": "Kyle Jazwa",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "C",
                "code": "PHY2004",
                "title": "Electricity and Magnetism",
                "coordinator": "Stefan Danilishin",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "MAT2009/MAT1002/MAT2004/PHY1001"
            },
            {
                "slot": "D",
                "code": "BIO2001",
                "title": "Cell Biology",
                "coordinator": "Martijn van Griensven",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "D",
                "code": "INT3003",
                "title": "Biomaterials",
                "coordinator": "C. Domingues Mota/P. Wieringa",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "CHE2001"
            },
            {
                "slot": "D",
                "code": "PHY1003",
                "title": "Mechanics",
                "coordinator": "Lorenzo Reverberi",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY1101"
            },
            {
                "slot": "D",
                "code": "PHY2011",
                "title": "Special Relativity",
                "coordinator": "Jacco de Vries",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY2001/PHY1003"
            },
            {
                "slot": "E",
                "code": "INT1003",
                "title": "Introduction to Biomedical Engineering",
                "coordinator": "Daan van Beek",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "E",
                "code": "INT1007",
                "title": "Introduction to Earth Sciences",
                "coordinator": "Jesse Hennekam",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "E",
                "code": "INT3008",
                "title": "Regenerative Medicine",
                "coordinator": "David Kilian",
                "corequisite": false,
                "prerequisite": true,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "BIO2001+CHE2001"
            },
            {
                "slot": "E",
                "code": "CHE3011",
                "title": "Instrumental Analysis",
                "coordinator": "Annelies van der Bok",
                "corequisite": true,
                "prerequisite": true,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": "CHE3010",
                "prerequisiteCodes": "CHE2004"
            },
            {
                "slot": null,
                "code": "PRA1008",
                "title": "Basics of Palaeontology",
                "coordinator": "Jesse Hennekam",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonAM", "MonPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA1009",
                "title": "Neuro Anatomy Skills",
                "coordinator": "Daan van Beek",
                "corequisite": true,
                "prerequisite": false,
                "days": ["TueAM", "TuePM", "ThuAM", "ThuPM"],
                "corequisiteOf": "NEU1001",
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2005",
                "title": "Advanced Molecular Laboratory Skills",
                "coordinator": "Erik Steen Redeker",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "MonPM", "WedAM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2011",
                "title": "Exploring the World of Plants",
                "coordinator": "Phil Klahs",
                "corequisite": true,
                "prerequisite": false,
                "days": ["TueAM", "TuePM", "ThuAM", "ThuPM"],
                "corequisiteOf": "BIO2003",
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2014",
                "title": "Genetics",
                "coordinator": "S. Olieslagers / D. Cortens",
                "corequisite": true,
                "prerequisite": true,
                "days": ["MonAM", "MonPM", "WedAM", "WedPM", "FriAM", "FriPM"],
                "corequisiteOf": "BIO2007",
                "prerequisiteCodes": "BIO2001"
            },
            {
                "slot": null,
                "code": "PRA2028",
                "title": "Mathematics and Art",
                "coordinator": "Mariet Hofstee",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2029",
                "title": "3D Visualizations and Transformations",
                "coordinator": "May Lee",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TueAM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2031",
                "title": "Python Programming Language",
                "coordinator": "Ruth Grosseholz",
                "corequisite": false,
                "prerequisite": true,
                "days": ["WedAM", "WedPM", "ThuAM", "ThuPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "MAT2007"
            },
            {
                "slot": null,
                "code": "PRA2032",
                "title": "Fundamentals of Organic Chemistry Laboratory",
                "coordinator": "Hanne Dilliën",
                "corequisite": true,
                "prerequisite": false,
                "days": ["TueAM", "TuePM", "ThuAM", "ThuPM", "FriAM", "FriPM"],
                "corequisiteOf": "CHE2009",
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA3012",
                "title": "Advanced Electronics",
                "coordinator": "Bart van Grinsven",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "MonPM", "WedAM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2006+PHY2006"
            },
            {
                "slot": null,
                "code": "PRA3014",
                "title": "Spectroscopic Methods",
                "coordinator": "Annelies van der Bok",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "MonPM", "TueAM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "CHE2004"
            },
            {
                "slot": null,
                "code": "PRA3017",
                "title": "Applied Cell Biology",
                "coordinator": "Silvia Bolognin",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TueAM", "TuePM", "ThuAM", "ThuPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2014"
            },
            {
                "slot": null,
                "code": "PRA3024",
                "title": "Analysis of Big Data in Physics",
                "coordinator": "Jacco de Vries & Maarten v. Veghel",
                "corequisite": false,
                "prerequisite": true,
                "days": ["WedAM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "MAT2007"
            },
            {
                "slot": null,
                "code": "PRA3504",
                "title": "The Academic Life Cycle",
                "coordinator": "Kyle Jazwa",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "MonPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2015"
            }
        ]
    }
    ];