const P5_COURSES = [
    {
        "version": "1.0",
        "period": "5",
        "validFrom": "2026-2027",
        "courses": [
            {
                "slot": "A",
                "code": "CHE2010",
                "title": "General Chemistry",
                "coordinator": "Chris Bahn",
                "corequisite": true,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": "PRA2034",
                "prerequisiteCodes": "CHE1101"
            },
            {
                "slot": "A",
                "code": "BIO3001",
                "title": "Molecular Biology",
                "coordinator": "Kathia Jimenez Monroy",
                "corequisite": true,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": "PRA3003",
                "prerequisiteCodes": "BIO2001+BIO2007"
            },
            {
                "slot": "A",
                "code": "PHY2002",
                "title": "Thermodynamics and Statistical Mechanics",
                "coordinator": "Slava Vieru",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "MAT2006/MAT2009"
            },
            {
                "slot": "A",
                "code": "INT1005",
                "title": "Commercializing Science & Technology",
                "coordinator": "Jermain Kaminski",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonAM", "TueAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "BIO3004",
                "title": "Animal Behaviour",
                "coordinator": "Linnea van Griethuijsen",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "BIO2004+BIO2005"
            },
            {
                "slot": "B",
                "code": "PHY2007",
                "title": "Optics",
                "coordinator": "Sebastian Steinlechner",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY2003"
            },
            {
                "slot": "B",
                "code": "INT2008",
                "title": "Molecular Toxicology",
                "coordinator": "Misha Vrolijk",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "B",
                "code": "INT3011",
                "title": "Landscape Archaeology",
                "coordinator": "Kyla Jazwa",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2009/INT2012/PRA2024/PRA2015"
            },
            {
                "slot": "B",
                "code": "MAT2004",
                "title": "Linear Algebra",
                "coordinator": "Martin Frohn",
                "corequisite": false,
                "prerequisite": false,
                "days": ["MonPM", "TuePM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "C",
                "code": "BIO2002",
                "title": "Ecology",
                "coordinator": "John Sloggett",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "C",
                "code": "BIO2006",
                "title": "Biotechnology",
                "coordinator": "David Cortens",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "BIO2007+PRA2014"
            },
            {
                "slot": "C",
                "code": "CHE3012",
                "title": "Nanomaterials and Catalysis",
                "coordinator": "Annelies van der Bok",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": "CHE2009",
                "prerequisiteCodes": "CHE3010"
            },
            {
                "slot": "C",
                "code": "PHY3006",
                "title": "General Relativity",
                "coordinator": "Gideon Koekoek",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY3002/PHY2011"
            },
            {
                "slot": "C",
                "code": "MAT2005",
                "title": "Probability and Statistics",
                "coordinator": "Otti d'Huys",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TueAM", "WedAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "MAT2006"
            },
            {
                "slot": "D",
                "code": "BIO3003",
                "title": "Medical Microbiology",
                "coordinator": "Frank Stassen",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": "PRA3010",
                "prerequisiteCodes": "BIO2001+BIO2007"
            },
            {
                "slot": "D",
                "code": "MAT1007",
                "title": "Mathematical Tools for Scientists",
                "coordinator": "Mariët Hofstee",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "D",
                "code": "INT2014",
                "title": "Imaging Engineering",
                "coordinator": "Gavin Hazell",
                "corequisite": false,
                "prerequisite": false,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "D",
                "code": "PHY2005",
                "title": "Fundamentals of Quantum Mechanics",
                "coordinator": "Keri Vos",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": "PHY2001",
                "prerequisiteCodes": "MAT2004/MAT2006/MAT2008"
            },
            {
                "slot": "E",
                "code": "NEU1003",
                "title": "Computational Neuroscience",
                "coordinator": "Renaud Jolivet",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "E",
                "code": "PHY3005",
                "title": "Electrodynamics",
                "coordinator": "Stefan Danilishin",
                "corequisite": false,
                "prerequisite": true,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PHY2004+MAT2009+PHY2011"
            },
            {
                "slot": "E",
                "code": "CHE2007",
                "title": "Solid State Chemistry",
                "coordinator": "Giuditta Perversi",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": "E",
                "code": "INT2009",
                "title": "Biophysics",
                "coordinator": "Anjusha Mathew",
                "corequisite": false,
                "prerequisite": true,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "CHE2006+BIO2001+CHE2004+INT2010+INT2014+PRA2020+PRA2005"
            },
            {
                "slot": "E",
                "code": "PHY2008",
                "title": "Solar System Astronomy",
                "coordinator": "Chad Ellington",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA1003",
                "title": "Basic Physics Laboratory",
                "coordinator": "Suzan du Pree",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedAM", "FriAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA1005",
                "title": "Data Collection Techniques in Neuroscience",
                "coordinator": "Mark Roberts",
                "corequisite": false,
                "prerequisite": false,
                "days": ["WedPM", "ThuAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": null
            },
            {
                "slot": null,
                "code": "PRA2007",
                "title": "Physics Laboratory",
                "coordinator": "Chris Pawley & Maarten van Veghel",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonAM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA1003"
            },
            {
                "slot": null,
                "code": "PRA2008",
                "title": "Physical Chemistry",
                "coordinator": "Slava Vieru",
                "corequisite": false,
                "prerequisite": true,
                "days": ["FriPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2034+PHY2002+CHE3007"
            },
            {
                "slot": null,
                "code": "PRA2009",
                "title": "Field Skills in Biology",
                "coordinator": "Phil Klahs",
                "corequisite": false,
                "prerequisite": true,
                "days": ["TuePM", "WedPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA1102"
            },
            {
                "slot": null,
                "code": "PRA2020",
                "title": "Practical Mass Spectrometry",
                "coordinator": "Anjusha Mathew",
                "corequisite": false,
                "prerequisite": true,
                "days": ["ThuPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "INT2010"
            },
            {
                "slot": null,
                "code": "PRA2023",
                "title": "Astronomical Observing Techniques",
                "coordinator": "Chad Ellington",
                "corequisite": false,
                "prerequisite": true,
                "days": ["MonPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA1003/PHY2008/PHY2009/PHY2010"
            },
            {
                "slot": null,
                "code": "PRA2034",
                "title": "General Chemistry Laboratory",
                "coordinator": "Chris Bahn",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TueAM", "FriPM"],
                "corequisiteOf": "CHE2010",
                "prerequisiteCodes": "PRA1101/PRA1102"
            },
            {
                "slot": null,
                "code": "PRA3003",
                "title": "Molecular Biology",
                "coordinator": "Kathia Jimenez Monroy",
                "corequisite": true,
                "prerequisite": true,
                "days": ["TuePM", "FriAM"],
                "corequisiteOf": "BIO3001",
                "prerequisiteCodes": "PRA2014+core 1000-level"
            },
            {
                "slot": null,
                "code": "PRA3010",
                "title": "Microbiology",
                "coordinator": "Frank Stassen",
                "corequisite": true,
                "prerequisite": true,
                "days": ["WedAM", "ThuPM"],
                "corequisiteOf": "BIO3003",
                "prerequisiteCodes": "BIO2001+BIO2007"
            },
            {
                "slot": null,
                "code": "PRA3011",
                "title": "The Limburg Landscape",
                "coordinator": "Phil Klahs",
                "corequisite": false,
                "prerequisite": true,
                "days": ["FriPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2009"
            },
            {
                "slot": null,
                "code": "PRA3025",
                "title": "Science Communication: Curating Science Exhibits",
                "coordinator": "May Lee & Kyle Jazwa",
                "corequisite": false,
                "prerequisite": true,
                "days": ["ThuPM"],
                "corequisiteOf": null,
                "prerequisiteCodes": "PRA2027"
            }
        ]
    }
];